### ISSUE TITLE
The lab's test don't test the removal of the event

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/angular-using-dom-events-lab#2]
The ReadMe before this lab goes over the `scope.$on('destroy', callBack(){})` and this lab specifically says to add that, but there is no test for it. The only test is just to see if you can set up a 'click to increment' feature which has been done before. 

I'm also not so sure what 'destroying a directive' looks like (this is referenced as the reason for using `.$on('destroy')`. Perhaps this lab should encompass creating, destroying, event listeners and directives?

@ipc103 @PeterBell

**Comment by PeterBell** [comment]
Good comments! Want to take a stab at a PR that might improve this @aturkewi ?

**Comment by aturkewi** [comment]
@PeterBell I think I'm still working on learning this a bit too much to be creating a new example (I'd probably just be copy pasting from another example :( )

**Comment by PeterBell** [comment]
Hey @aturkewi got it. @AnnJohn any idea who might be best able to work on this?

**Comment by AnnJohn** [comment]
@PeterBell, the best person right now would be Ian but he's on break and then switching to labs. I can see if there's any way he can spend time going through really outstanding Angular issues. Thanks!

**Comment by PeterBell** [comment]
Sounds great - thanks @AnnJohn

**Comment by steveafrost** [comment]
Feeling the same way as Avidor on this one. I'd love a way to test the $destroy functionality.
